# Specifica la versione della sintassi di Docker Compose
version: '3.8'

# Definisce i servizi (i container) che vogliamo avviare
services:
  # Nome del nostro servizio di database
  postgres-db:
    # L'immagine Docker da usare. Prenderà l'ultima versione ufficiale di PostgreSQL.
    image: postgres
    # Nome che vogliamo dare al container una volta avviato
    container_name: project_db_container
    # Variabili d'ambiente per configurare PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # <-- IMPOSTA QUESTA
      POSTGRES_DB: project_management_db
    # Mappa le porte. La porta 5432 del container viene esposta sulla porta 5432 del tuo computer.
    ports:
      - "5432:5432"
    # (Opzionale ma consigliato) Garantisce che i dati del database sopravvivano anche se il container viene rimosso e ricreato.
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Definisce i volumi nominati
volumes:
  postgres-data: